"""Paired burden of multiplicity from trade-offs generated by this notebook.

No model training or joint-recourse reruns. All inference uses the saved
cohort, model ordering, standardized coordinates, and feature constraints.
Worst-individual validity means min over models of their factual-average
individual validity, computed WITHIN seed before averaging across seeds.
"""
import hashlib
import importlib.metadata
import json
from pathlib import Path
import time
import numpy as np
import pandas as pd
import torch
from torch.nn import functional as F
from . import recourse_core as rc
from . import recourse_results as rr
from . import recourse_statistics as rs
from . import recourse_reporting as rp
from . import recourse_convergence as rg

REVISION='v6-multiplicity-burden-v1'
PROFILES={
    'quick':dict(pgd_steps=40,pgd_restarts=2,step_fraction=.1,tree_time_limit=.5),
    'intermediate':dict(pgd_steps=200,pgd_restarts=3,step_fraction=.1,tree_time_limit=1.),
    'full':dict(pgd_steps=400,pgd_restarts=5,step_fraction=.1,tree_time_limit=2.),
}
GROUP=['source_version','source_mode','dataset','family','aggregation','config','n_models','budget']
METRICS={
    'worst_individual_validity':'Worst individual-model validity (%)',
    'all_individually_validity':'Every model individually attainable (%)',
    'joint_validity':'Saved joint-recourse validity (%)',
    'burden_worst':'Worst-individual minus joint validity (percentage points)',
    'burden_all':'Every-individual minus joint validity (percentage points)',
    'mean_individual_validity':'Mean individual-model validity (%)',
    'unresolved_fraction':'Unresolved individual searches (%)',
    'certified_infeasible_fraction':'Certified individual infeasibility (%)',
}


def settings(Quick=True):
    from .recourse_campaign import mode_name
    mode=mode_name(Quick)
    if mode not in PROFILES:raise ValueError('Burden search mode must be quick, intermediate or full')
    return dict(mode=mode,**PROFILES[mode],threshold=.5,abs_gap=1e-6,
                cohort='all saved source factuals and seeds; no mode-based subsampling')


def find_saved_tradeoffs(results_root, version='v6', mode='quick', sections=('cost_validity',)):
    """Select the latest saved campaign per explicit version/mode/section.

Only one level is inspected, never a recursive scan of model/event files.
The selected paths are printed and recorded. No cross-version auto-fallback.
"""
    paths=[]
    for section in sections:
        if section not in {'cost_validity','tree_tradeoff'}:raise ValueError('Expected a trade-off section')
        root=Path(results_root)/version/str(mode)/section
        candidates=sorted(root.glob('*/all_results.csv')) if root.exists() else []
        if candidates:paths.append(candidates[-1].parent)
    if not paths:raise FileNotFoundError(f'No saved trade-offs for {version}/{mode}/{sections}')
    return paths


def _resolve_sources(sources):
    if isinstance(sources,(str,Path,pd.DataFrame)):sources=[sources]
    runs=[]
    for source in sources:
        if isinstance(source,pd.DataFrame):
            parent=Path(source.attrs.get('campaign_directory','.'))
            values=source['Run Directory'].dropna().unique()
        else:
            p=Path(source).expanduser().resolve()
            if (p/'manifest.json').exists() and (p/'instances.jsonl').exists():
                runs.append(p);continue
            summary=p if p.suffix=='.csv' else p/'all_results.csv'
            if not summary.exists():raise FileNotFoundError(f'Expected a run folder or campaign all_results.csv: {p}')
            parent=summary.parent
            values=pd.read_csv(summary,usecols=['Run Directory'])['Run Directory'].dropna().unique()
        for value in values:
            recorded=Path(value)
            # Prefer files alongside the supplied CSV, so moved/downloaded results work.
            local=parent/'runs'/recorded.name
            p=local if local.exists() else recorded
            if not (p/'instances.jsonl').exists():raise FileNotFoundError(f'Missing source run: {p}')
            runs.append(p.resolve())
    return list(dict.fromkeys(runs))


def _file_hash(path):
    h=hashlib.sha256()
    with Path(path).open('rb') as stream:
        for chunk in iter(lambda:stream.read(1024*1024),b''):h.update(chunk)
    return h.hexdigest()


def _hash(value):
    return hashlib.sha256(json.dumps(rr.jsonable(value),sort_keys=True,separators=(',',':')).encode()).hexdigest()


def _rows(path):
    """Only the saved ORPM joint outcomes; other methods are not substituted."""
    fields=['dataset','family','aggregation','seed','fold','instance_id','budget','actual_models',
            'requested_counts','point','factual','probabilities','valid','status','trajectory_file','actionability_policy']
    rows=[]
    for row in rr.read_records(path):
        if row.get('method') in {'ORPM','ORPM-tree'} and row.get('instance_id') is not None:
            if not all(k in row for k in ['point','factual','valid','trajectory_file']):
                raise ValueError(f'Missing saved factual/point/constraints in {path}')
            rows.append({k:row[k] for k in fields if k in row})
    return rows


def _group(manifest,row):
    counts=row.get('requested_counts')
    family=row.get('family','differentiable')
    config=('%d LR + %d NN1 + %d NN2'%tuple(counts)) if counts else f'{row["actual_models"]} {family.replace("_"," ")} models'
    return dict(source_version=manifest.get('notebook_version','unknown'),
        source_mode=manifest['configuration'].get('mode','unknown'),dataset=row['dataset'],
        family=family,aggregation=row.get('aggregation','probability'),config=config,
        n_models=int(row['actual_models']),budget=float(row['budget']))


def prepare_sources(sources,datasets=None,validate_inputs=True,verbose=False):
    jobs=[];seen=set();seed_owners={}
    for path in _resolve_sources(sources):
        manifest=json.loads((path/'manifest.json').read_text())
        if manifest.get('status') not in {'completed','completed_with_errors'}:
            raise ValueError(f'Source run is not completed: {path}')
        rows=_rows(path)
        if datasets is not None:rows=[r for r in rows if r['dataset'] in datasets]
        if not rows:continue
        for row in rows:
            identity=tuple(_group(manifest,row)[k] for k in GROUP)+(row['seed'],row['instance_id'])
            seed_identity=identity[:-1]
            if seed_identity in seed_owners and seed_owners[seed_identity]!=path:
                raise ValueError('One seed/configuration/budget is split across source runs; choose a single cohort.')
            seed_owners[seed_identity]=path
            if identity in seen:
                raise ValueError('Overlapping cohorts from multiple source runs. Select one campaign per version/mode/configuration.')
            seen.add(identity)
        if not validate_inputs:
            jobs.append(dict(path=path,manifest=manifest,rows=rows))
            continue
        if verbose:print(f'  Checking saved inputs: {path.name} ({len(rows)} outcomes)',flush=True)
        # Checkpoint metadata and file changes invalidate source-session resume.
        inventory=[]
        for folder in sorted({path/f'seed_{r["seed"]}_fold_{r["fold"]}' for r in rows}):
            files=list(folder.glob('model_*.npz'))+list(folder.glob('models.json'))
            files+=list((folder/'optimization').glob('model_*/*'))
            for file in sorted(files):
                if file.is_file():inventory.append((str(file.relative_to(path)),_file_hash(file)))
        for row in rows:
            file=path/row['trajectory_file']
            with np.load(file,allow_pickle=False) as arrays:
                row['_lower']=arrays['constraint_lower'].copy()
                row['_upper']=arrays['constraint_upper'].copy()
                row['_immutable']=arrays['immutable_indices'].astype(int).tolist()
                if not np.array_equal(arrays['factual'],np.asarray(row['factual'],dtype=np.float32)):
                    raise ValueError(f'Saved factual does not match its trajectory: {file}')
        jobs.append(dict(path=path,manifest=manifest,rows=rows,inventory=inventory,
            fingerprint=_hash(dict(manifest=_file_hash(path/'manifest.json'),
                instances=_file_hash(path/'instances.jsonl'),models=inventory,
                constraints=[(r['_lower'],r['_upper'],r['_immutable']) for r in rows]))))
    if not jobs:raise ValueError('No completed saved ORPM trade-off outcomes match these sources/datasets')
    return jobs


def source_plan(sources,datasets=None):
    rows=[]
    for job in prepare_sources(sources,datasets,validate_inputs=False):
        for budget in sorted({r['budget'] for r in job['rows']}):
            data=[r for r in job['rows'] if r['budget']==budget]
            rows.append(dict(_group(job['manifest'],data[0]),
                saved_seeds=len({r['seed'] for r in data}),saved_instances=len(data),
                individual_evaluations=sum(r['actual_models'] for r in data),source_run=str(job['path'])))
    return pd.DataFrame(rows)


def _models(folder,is_tree):
    if is_tree:
        from . import recourse_trees as rt
        return [rt.TreeModel.load(p) for p in sorted((folder/'optimization').glob('model_*'))]
    return rr.load_models(folder)


def model_hash(model):
    h=hashlib.sha256()
    if hasattr(model,'trees'):
        h.update(_hash(dict(family=model.family,dimension=model.dimension,aggregation=model.aggregation)).encode())
        arrays=[(f'{i}/{k}',getattr(t,k)) for i,t in enumerate(model.trees)
                for k in ['left','right','feature','threshold','probability']]
    else:
        desc=rr._descriptor(model)
        h.update(_hash({k:desc[k] for k in ['class','linear_dimensions','feature_mask']}).encode())
        arrays=[(k,v.detach().cpu().numpy()) for k,v in sorted(model.state_dict().items())]
    for key,array in arrays:
        a=np.ascontiguousarray(array)
        h.update(key.encode());h.update(str((a.shape,str(a.dtype))).encode());h.update(a.tobytes())
    return h.hexdigest()


def _probability(model,point):
    with torch.no_grad():return float(model(point).reshape(-1)[0])


def individual_search(model,x0,budget,c,options,random_seed):
    """Only one model is queried. NN failures remain uncertified searches."""
    threshold=options['threshold'];started=time.perf_counter()
    points=[x0.numpy().copy()];probabilities=[_probability(model,x0)]
    if probabilities[0]>=threshold:
        return x0.clone(),dict(status='already_favorable',certified_infeasible=False,
            elapsed_seconds=0.,gradient_evaluations=0),dict(points=np.asarray(points),probabilities=np.asarray(probabilities))
    if budget==0 or np.array_equal(c.lower,c.upper):
        return x0.clone(),dict(status='singleton_feasible_set',certified_infeasible=True,
            elapsed_seconds=0.,gradient_evaluations=0),dict(points=np.asarray(points),probabilities=np.asarray(probabilities))
    if hasattr(model,'trees'):
        from . import recourse_trees as rt
        solver=rt.TreeOracle([model],x0,budget,c,time_limit=options['tree_time_limit'],
                             abs_gap=options['abs_gap'],seed=random_seed)
        try:point=solver.solve([1.])
        finally:solver.close()
        info=dict(point.recourse_info)
        lower=info.get('lower_bound')
        info['certified_infeasible']=bool(lower is not None and lower>(1-threshold)**2+1e-7)
        info['individual_solver']='original_tree_weighted_oracle'
    elif rc.is_linear(model):
        oracle=rg.ConvexLogitOracle([model],x0.numpy(),budget,c,maxiter=options['pgd_steps'])
        candidate,info=oracle.solve([1.]);point=torch.tensor(candidate,dtype=x0.dtype)
        point=rc.project_l2_ball(point,x0,budget,constraints=c)
        info['certified_infeasible']=bool(info['lower_bound']>-np.log(threshold)/oracle.normalizer+1e-7)
        info['individual_solver']='convex_single_logistic'
    else:
        rng=np.random.default_rng(random_seed);best=x0.clone();best_p=probabilities[0];evaluations=0
        for restart in range(options['pgd_restarts']):
            if restart==0:x=x0.clone()
            else:
                d=rng.normal(size=len(x0));d[c.immutable]=0.
                d=d/max(np.linalg.norm(d),1e-12)*budget*rng.random()**(1/max(1,len(x0)-len(c.immutable)))
                x=rc.project_l2_ball(x0+torch.tensor(d,dtype=x0.dtype),x0,budget,constraints=c)
            for step in range(options['pgd_steps']+1):
                p=_probability(model,x);points.append(x.numpy().copy());probabilities.append(p)
                if np.isfinite(p) and p>best_p:best,best_p=x.clone(),p
                if best_p>=threshold or step==options['pgd_steps']:break
                z=x.detach().clone().requires_grad_(True)
                # Monotone in the favorable probability, with stable logit evaluation.
                loss=F.softplus(-model.logits(z)).mean()
                grad=torch.autograd.grad(loss,z)[0];evaluations+=1
                grad[c.immutable]=0.;norm=float(grad.norm())
                if not torch.isfinite(grad).all() or norm<1e-12:break
                rate=budget*options['step_fraction']*(.1+.9*.5*(1+np.cos(np.pi*step/options['pgd_steps'])))
                x=rc.project_l2_ball(z.detach()-rate*grad.detach()/norm,x0,budget,constraints=c).detach()
            if best_p>=threshold:break
        point=best
        info=dict(status='valid_witness_found' if best_p>=threshold else 'search_exhausted',
                  individual_solver='normalized_gradient_PGD_logit_BCE',certified_infeasible=False,
                  gradient_evaluations=evaluations,restarts=restart+1)
    if not rc.feasible(point,x0,budget,c) or not np.isfinite(_probability(model,point)):
        raise ValueError('Individual solver returned a non-finite/infeasible point')
    points.append(point.numpy().copy());probabilities.append(_probability(model,point))
    if probabilities[-1]>=threshold:info['certified_infeasible']=False
    info['elapsed_seconds']=time.perf_counter()-started
    return point,info,dict(points=np.asarray(points),probabilities=np.asarray(probabilities))


def summarize(records):
    """Apply min/mean in the correct order and form paired seed differences."""
    raw=pd.DataFrame(records)
    if raw.empty:return pd.DataFrame(),pd.DataFrame(),pd.DataFrame()
    seed_rows=[];individual_rates=[]
    for key,data in raw.groupby(GROUP+['seed'],dropna=False):
        identity=dict(zip(GROUP+['seed'],key));n=identity['n_models']
        if data.duplicated(['instance_id','model_index']).any():raise ValueError('Duplicate model/factual outcome')
        counts=data.groupby('instance_id').model_index.nunique()
        if not (counts==n).all():raise ValueError('Incomplete individual-model block; cannot compute worst-model validity')
        if data.groupby('instance_id').joint_valid.nunique().max()!=1:raise ValueError('Unpaired joint outcomes')
        matrix=data.pivot(index='instance_id',columns='model_index',values='individual_valid').astype(float)
        if set(matrix.columns)!=set(range(n)) or matrix.isna().any().any():raise ValueError('Models differ within a seed cohort')
        for index,rate in matrix.mean(axis=0).items():
            individual_rates.append(dict(identity,model_index=int(index),validity=100*rate,instances=len(matrix)))
        joint=float(data.groupby('instance_id').joint_valid.first().mean())
        worst=float(matrix.mean(axis=0).min());all_single=float(matrix.min(axis=1).mean())
        row=dict(identity,instances=len(matrix),
            worst_model_indices=[int(j) for j,v in matrix.mean(axis=0).items() if v==worst],
            worst_individual_validity=100*worst,
            all_individually_validity=100*all_single,joint_validity=100*joint,
            mean_individual_validity=100*matrix.to_numpy().mean(),
            burden_worst=100*(worst-joint),burden_all=100*(all_single-joint),
            unresolved_fraction=100*float((~data.individual_valid.astype(bool)&~data.certified_infeasible.astype(bool)).mean()),
            certified_infeasible_fraction=100*float(data.certified_infeasible.astype(bool).mean()))
        # Never clip negative differences. They would expose a pairing/search error.
        seed_rows.append(row)
    seeds=pd.DataFrame(seed_rows)
    bounds={k:((-100.,100.) if k.startswith('burden') else (0.,100.)) for k in METRICS}
    stats=rs.summarize_seed_frame(seeds,GROUP,list(METRICS),bounds)
    return seeds,stats,pd.DataFrame(individual_rates)


def export_results(records,root,show=False):
    import matplotlib.pyplot as plt
    seeds,stats,rates=summarize(records)
    if seeds.empty:return stats
    root=Path(root)
    pd.DataFrame(records).to_csv(root/'individual_results.csv',index=False)
    seeds.to_csv(root/'burden_seed_means.csv',index=False)
    rates.to_csv(root/'individual_model_validity.csv',index=False)
    stats.to_csv(root/'burden_summary.csv',index=False)
    for ds in stats.dataset.unique():
        for name,frame in [('multiplicity_burden_summary',stats),('multiplicity_burden_seed_means',seeds),('individual_model_validity',rates)]:
            rp.save_table(frame[frame.dataset.eq(ds)],root,ds,name)
    def plot(group,x,series_columns,name,title,xlabel):
        fig,axes=plt.subplots(1,2,figsize=(14,4.8))
        styles={'joint_validity':'-','worst_individual_validity':'--','all_individually_validity':':',
                'burden_worst':'-','burden_all':'--'}
        for series,sub in group.groupby(series_columns,dropna=False):
            label=' / '.join(str(s) for s in (series if isinstance(series,tuple) else (series,)))
            for ax,metrics in [(axes[0],['joint_validity','worst_individual_validity','all_individually_validity']),
                               (axes[1],['burden_worst','burden_all'])]:
                for metric in metrics:
                    d=sub[sub.metric.eq(metric)].sort_values(x)
                    y,=ax.plot(d[x],d['mean'],styles[metric],marker='o',label=f'{label}: {METRICS[metric].split(" (")[0]}')
                    ax.fill_between(d[x].to_numpy(float),d.ci_low.to_numpy(float),d.ci_high.to_numpy(float),color=y.get_color(),alpha=.12)
        axes[0].set(ylabel='Achieved validity (%)',ylim=(0,103))
        axes[1].set(ylabel='Validity burden (percentage points)');axes[1].axhline(0,color='black',lw=.7)
        for ax in axes:ax.set_xlabel(xlabel);ax.grid(alpha=.2);ax.legend(fontsize=7)
        fig.suptitle(title+'\nPointwise 95% seed-t CIs; missing intervals omitted. Same saved factual cohort.')
        fig.tight_layout();rp.save_figure(fig,root,group.dataset.iloc[0],name,show)
    base=['source_version','source_mode','dataset','family','aggregation']
    for key,group in stats.groupby(base,dropna=False):
        version,mode,ds,family,agg=key
        prefix=f'multiplicity_{version}_{mode}_{family}_{agg}'
        for config,sub in group.groupby('config'):
            title_config=config
            if family=='random_forest':title_config+=' (hard voting)' if agg=='hard_vote' else ' (probability averaging)'
            plot(sub,'budget',['config'],prefix+'_'+rp.safe(config)+'_vs_budget',
                 f'{rp.dataset_label(ds)} | {title_config} | source {version}/{mode}',
                 'Recourse budget (standardized L2 distance)')
        for budget,sub in group.groupby('budget'):
            if sub.n_models.nunique()>1:
                plot(sub,'n_models',['family'],prefix+f'_budget_{budget:g}_vs_size',
                     f'{rp.dataset_label(ds)} | budget {budget:g} | source {version}/{mode}',
                     'Number of competing models')
    return stats


def run_from_saved(sources,Quick=True,results_root=None,resume=True,datasets=None,show=False):
    """Add individual-model searches to saved trade-offs, with content-based cache.

Search mode controls solver effort, NOT source seeds/factuals. Joint outcomes
are reread per instance; aggregate summary percentages are never reused for
a different cohort. Repeated runs/configurations share identical singleton
queries only when model weights, factual, budget, constraints and options match.
"""
    if rr.current_run() is not None:raise RuntimeError('Run the burden experiment outside an active experiment call')
    options=settings(Quick)
    print('Loading and validating saved models, factuals, and constraints...',flush=True)
    jobs=prepare_sources(sources,datasets,verbose=True)
    root=Path(results_root or rr.RESULTS_ROOT or (rc.PROJECT_ROOT/'results')).resolve()
    base=root/rr.NOTEBOOK_VERSION/options['mode']/'multiplicity_burden';base.mkdir(parents=True,exist_ok=True)
    codes={name:_file_hash(Path(__file__).parent/name) for name in
           ['recourse_multiplicity.py','recourse_core.py','recourse_trees.py','recourse_convergence.py',
            'recourse_statistics.py','recourse_reporting.py','recourse_results.py']}
    versions={}
    for name in ['torch','numpy','scipy','gurobipy','scikit-learn']:
        try:versions[name]=importlib.metadata.version(name)
        except importlib.metadata.PackageNotFoundError:versions[name]=None
    protocol=dict(revision=REVISION,options=options,sources=[dict(path=str(j['path']),fingerprint=j['fingerprint']) for j in jobs],
        source_code=codes,packages=versions,threshold=.5,joint_method='saved ORPM / ORPM-tree',
        warm_witness='Already-favorable factuals and verified saved joint points prove singleton attainability; no search needed.',
        interpretation='Achieved-search burden; NN failure or tree timeout does not prove infeasibility.',
        inference='Worst model is selected within each seed; paired differences then use equal-weight seed-t CIs.')
    fingerprint=_hash(protocol);out=None
    if resume:
        for p in sorted(base.glob('*/burden_manifest.json'),reverse=True):
            if json.loads(p.read_text()).get('fingerprint')==fingerprint:out=p.parent;break
    if out is None:out=base/rr._stamp();out.mkdir()
    rr.atomic_json(out/'burden_manifest.json',dict(protocol,fingerprint=fingerprint,status='running'))
    source=out/'source';source.mkdir(exist_ok=True)
    for name in codes:(source/name).write_bytes((Path(__file__).parent/name).read_bytes())
    cache=base/'individual_cache';cache.mkdir(exist_ok=True)
    count=sum(r['actual_models'] for j in jobs for r in j['rows'])
    print(f'Multiplicity burden: {len(jobs)} saved runs; {count:,} model/factual/budget evaluations. '
          'Source seeds and instances are retained. Valid witnesses and matching cached queries skip optimization.',flush=True)
    print('Outputs:',out,flush=True)
    records=[];errors=[];solves=hits=witnesses=0
    # This canonical file is regenerated on resume from verified sources and cached singleton solves.
    (out/'individual_results.jsonl').write_text('')
    started=time.perf_counter()
    try:
        for ji,job in enumerate(jobs):
            path=job['path'];models_by_seed={};hashes_by_seed={}
            print(f'  Source {ji+1}/{len(jobs)}: {path.name} ({len(job["rows"])} saved factual/budget outcomes)',flush=True)
            for ri,row in enumerate(job['rows']):
                identity=_group(job['manifest'],row);seed_key=(row['seed'],row['fold'])
                folder=path/f'seed_{row["seed"]}_fold_{row["fold"]}'
                if seed_key not in models_by_seed:
                    models_by_seed[seed_key]=_models(folder,identity['family']!='differentiable')
                    hashes_by_seed[seed_key]=[model_hash(m) for m in models_by_seed[seed_key]]
                models=models_by_seed[seed_key]
                if len(models)!=identity['n_models']:raise ValueError(f'Saved model count mismatch: {folder}')
                x0=torch.tensor(row['factual'],dtype=torch.float32);joint=torch.tensor(row['point'],dtype=torch.float32)
                c=rc.Constraints(np.asarray(row['_lower']),np.asarray(row['_upper']),row['_immutable'],row.get('actionability_policy','saved'))
                if not rc.feasible(x0,x0,row['budget'],c):raise ValueError('Saved factual violates its constraints')
                probs=np.array([_probability(m,joint) for m in models]);joint_feasible=rc.feasible(joint,x0,row['budget'],c)
                if not np.allclose(probs,row['probabilities'],atol=2e-6,rtol=1e-6):
                    raise ValueError(f'Reloaded models do not reproduce saved joint predictions: {folder}')
                if row['valid'] and not (joint_feasible and (probs>=options['threshold']).all()):
                    raise ValueError('Saved successful joint recourse fails revalidation')
                for mi,model in enumerate(models):
                    entry=dict(identity,seed=row['seed'],fold=row['fold'],instance_id=row['instance_id'],model_index=mi,
                        model_hash=hashes_by_seed[seed_key][mi],source_run=str(path),source_status=row['status'],
                        factual=row['factual'],joint_point=row['point'],
                        joint_valid=bool(row['valid']),joint_actual_valid=bool(joint_feasible and (probs>=options['threshold']).all()),
                        joint_probability=float(probs[mi]),budget=float(row['budget']))
                    # A positive factual or saved feasible point already witnesses the singleton problem.
                    if _probability(model,x0)>=options['threshold']:
                        point=x0.clone();info=dict(status='already_favorable',certified_infeasible=False,elapsed_seconds=0.)
                        origin='factual';witnesses+=1;cache_key=None
                    elif joint_feasible and probs[mi]>=options['threshold']:
                        point=joint.clone();info=dict(status='saved_joint_witness',certified_infeasible=False,elapsed_seconds=0.)
                        origin='saved_joint_point';witnesses+=1;cache_key=None
                    else:
                        cache_key=_hash(dict(model=entry['model_hash'],factual=x0.numpy(),budget=row['budget'],
                            lower=c.lower,upper=c.upper,immutable=c.immutable,options=options,code=codes,packages=versions))
                        record_path=cache/(cache_key+'.json');trace_path=cache/(cache_key+'.npz')
                        cached=False
                        if resume and record_path.exists() and trace_path.exists():
                            saved=json.loads(record_path.read_text())
                            if saved.get('trace_sha256')==_file_hash(trace_path):
                                point=torch.tensor(saved['point'],dtype=x0.dtype);info=saved['info'];cached=True;hits+=1
                        if not cached:
                            try:
                                point,info,trace=individual_search(model,x0,row['budget'],c,options,int(cache_key[:8],16)%2147483647)
                            except Exception as exc:
                                point=x0.clone();info=dict(status='solver_error',error=f'{type(exc).__name__}: {exc}',
                                    certified_infeasible=False,elapsed_seconds=None)
                                errors.append(dict(entry,error=info['error']))
                            else:
                                rr._npz(trace_path,dict(trace,factual=x0.numpy(),constraint_lower=c.lower,
                                    constraint_upper=c.upper,immutable_indices=np.asarray(c.immutable,dtype=int),budget=row['budget']))
                                rr.atomic_json(record_path,dict(key=cache_key,model_hash=entry['model_hash'],
                                    options=options,packages=versions,point=point,info=info,trace_sha256=_file_hash(trace_path)))
                            solves+=1
                        origin='cache' if cached else 'individual_search'
                    probability=_probability(model,point)
                    if not rc.feasible(point,x0,row['budget'],c) or not np.isfinite(probability):
                        raise ValueError('Cached or computed singleton result failed validation')
                    valid=bool(probability>=options['threshold'])
                    entry.update(individual_valid=valid,individual_probability=probability,
                        certified_infeasible=bool(info.get('certified_infeasible',False) and not valid),
                        point=point.tolist(),cost=float(torch.linalg.vector_norm(point-x0)),
                        origin=origin,cache_key=cache_key,status=info['status'],solver=info)
                    records.append(entry);rr._append(out/'individual_results.jsonl',entry)
                rr.atomic_json(out/'progress.json',dict(completed_evaluations=len(records),total_evaluations=count,
                    new_searches=solves,cache_hits=hits,known_valid_witnesses=witnesses,errors=len(errors),
                    elapsed_seconds=time.perf_counter()-started))
                if (ri+1)%5==0 or ri+1==len(job['rows']):
                    print(f'    {ri+1}/{len(job["rows"])} source outcomes; {len(records):,}/{count:,} individual '
                          f'evaluations; {solves:,} searches, {hits:,} cache hits, {witnesses:,} known witnesses',flush=True)
            # Safe to aggregate after a complete source run (full model blocks).
            seeds,summary,rates=summarize(records)
            seeds.to_csv(out/'burden_seed_means.csv',index=False);summary.to_csv(out/'burden_summary.csv',index=False)
            rr.atomic_json(out/'errors.json',errors)
        summary=export_results(records,out,show)
    except BaseException as exc:
        rr.atomic_json(out/'burden_manifest.json',dict(protocol,fingerprint=fingerprint,
            status='interrupted' if isinstance(exc,(KeyboardInterrupt,SystemExit)) else 'failed',error=str(exc)))
        raise
    rr.atomic_json(out/'burden_manifest.json',dict(protocol,fingerprint=fingerprint,
        status='completed_with_errors' if errors else 'completed',evaluations=len(records),new_searches=solves,
        cache_hits=hits,known_valid_witnesses=witnesses,errors=len(errors),elapsed_seconds=time.perf_counter()-started))
    summary.attrs.update(campaign_directory=str(out),search_errors=errors)
    print(f'Completed: {solves} new searches, {hits} cache hits, {witnesses} known-valid witnesses. Saved {out}',flush=True)
    return summary
